---
apiVersion: v1
kind: Service
metadata:
  name: naked-bardin-haus-app
spec:
  type: ClusterIP
  ports:
  - port: 8080
    protocol: TCP
  selector:
    name: naked
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: naked-bardin-haus-vhost
spec:
  rules:
  - host: bardin.haus
    http:
      paths:
      - backend:
          serviceName: naked-bardin-haus-app
          servicePort: 8080
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: naked
spec:
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  replicas: 1
  template:
    metadata:
      labels:
        name: naked
    spec:
      containers:
      - name: naked-bardin-haus-app
        image: docker.repo.mvn.link/bigmaven:1234
        ports:
        - containerPort: 8080
        command:
        - "bundle"
        - "exec"
        - "puma"
        - "-C"
        - "puma.rb"
        env: &1
        - name: APP_ENV
          value: production
